name: the_dart_side
description: Repositorio de ejemplos para en canal de The Dart Side de Argel Bejarano (@ArkangelB) y Diego Velasquez (@Diegoveloper).

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"


flutter:
  uses-material-design: true

  # assets example:
  assets:
    - assets/images/

  # fonts example:
  fonts:
    - family: Starjedi
      fonts:
        - asset: assets/fonts/Starjedi.ttf
    - family: Starjhol
      fonts:
        - asset: assets/fonts/Starjhol.ttf
    - family: Starjout
      fonts:
        - asset: assets/fonts/Starjout.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/dash_icon.png"
